### ISSUE TITLE
Pagination, sorting, and filtering for TaskLogEntry list

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#106]
The log items are potentially very large, and there will be at least 1x/day. We need pagination, sorting, filtering for these items, as for the exiting employees.

**Comment by hangler** [comment]
Ready for testing. @robinwn I'll assign you as the tester for this 😉

**Comment by robinwn** [comment]
lgtm

![image](https://user-images.githubusercontent.com/17856118/85465770-08f44180-b55e-11ea-97fb-45b760b4130f.png)

**Comment by hangler** [comment]
Great! Sorry, I only assigned you because you had mentioned maybe hiding the super long output :-)
