### ISSUE TITLE
Serialize date [time] in  ISO 8601 form

### ISSUE THREAD

**Issue by robinwn** [bcgov/ExitSurveyAdmin#110]
Various date and time columns on the employee csv export should be in ISO 8601 format.  Use date & time form except for columns where only the date is meaningful, then just the date.

**Comment by hangler** [comment]
@karmour Could I ask you to kindly sign off that this is complete? Thanks!

**Comment by karmour** [comment]
Looks fine to me -- the only columns that include a time as well as a date are the "createdTs" and "modifiedTs" columns, which I presume relate to creating the record/timeline and modifying it. Date formats look good across the export file.

**Comment by hangler** [comment]
Yes, that's exactly what those fields refer to. Great, closing this.
