### ISSUE TITLE
Status filter not working correctly

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#115]
@aclowery:

> Status filter not working correctly: selected "New or Survey Complete" and can still see "Employee not exiting" in the list.

**Comment by hangler** [comment]
Occurs when filtering on multiple criteria, and one of the criteria does not exist.

**Comment by karmour** [comment]
- Multiple filters appear to work as expected now. Filters now remain after setting and can more easily be combined with other filters -- to remove filters, admin can hit "reset all filters" or cancel each filter individually.

**Comment by hangler** [comment]
Great!
