### ISSUE TITLE
Change which fields are editable and add "preferred x" fields

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#118]
@aclowery:

> Unsure if we need to be able to manually change anything other than the Current Status - thoughts?

**Comment by hangler** [comment]
Related, from @karmour's comments:

> Can make a change to First Name but not to Last Name.

This is currently by design.

**Comment by hangler** [comment]
Also related: is there ever a case where we would want the updated fields re-written by a CSV upload?

**Comment by hangler** [comment]
• Add a Preferred Name
• Add a Preferred Email and Preferred Address
• Push preferred fields in preference to system-generated ones
• Remove editability from Reason and Appointment Status

**Comment by hangler** [comment]
This is now deployed, kindly test and let me know how it goes!

**Comment by aclowery** [comment]
@hangler the preferred fields are good! The ability to update Status is good, and is visible right away when you return to the main page. Are the edits to the preferred name/email address fields also supposed to be visible on the main page? This doesn't necessarily matter, just as long as the preferred name/email address would be pushed into CallWeb.

**Comment by hangler** [comment]
@aclowery The preferred first name/email are not currently visible in the main list. I know you say it doesn't matter, but what's your preference? It's very easy to change it to show whichever you prefer. And yes, it's only the preferred name/email that are pushed into CallWeb.

**Comment by aclowery** [comment]
@hangler if we did have the preferred name/email showing up in the main list, would the filter/search be linked to preferred name/email also? If this is the case, then yes, I think having preferred name and email to search by and see in the main list would be my preference. Thanks!

**Comment by hangler** [comment]
OK. By the same token, we will also search by preferred email, unless you tell me otherwise :-)

**Comment by karmour** [comment]
Preferred fields show up in filter. Have not yet tested whether preferred fields are overwritten by a new CSV upload.

**Comment by karmour** [comment]
Confirmed that Preferred fields are not overwritten upon next CSV upload.

**Comment by hangler** [comment]
👍
