### ISSUE TITLE
Add filters without clearing existing ones

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#122]
@karmour can you provide a bit more feedback on this issue as reported in the Excel testing file? You wrote:

> Cannot set multiple filters to one field (e.g., Reason or Current Status)

You should be able to set multiple filter values in the dropdown for these filters, as it is (or should be) a multi-select. See image below. Please let me know if I'm misinterpreting this. Thank you!

<img width="318" alt="Screen Shot 2020-06-15 at 9 03 25 AM" src="https://user-images.githubusercontent.com/3538990/84680131-14ed5d00-aee7-11ea-87bd-222a1c27b274.png">

**Comment by karmour** [comment]
I just tried again -- yes it looks like I can set multiple at once, I just have to click them one at a time prior to hitting 'set filter'.  My screen doesn't look the same as yours but it does work!

**Comment by hangler** [comment]
Per our discussion this morning I am shifting this to be a ticket about the ability to add filters on the same field after they have already been set on that field.

**Comment by hangler** [comment]
This should be done.
