### ISSUE TITLE
KeyCloak login error

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#123]

**Comment by hangler** [comment]
There is a chance this has to do with the silent renew, which is enabled but not working. Will investigate this.

**Comment by hangler** [comment]
@karmour @aclowery Have you noticed the login issue in Chrome since last week?

**Comment by karmour** [comment]
There have been some odd page flickers upon navigating to the link, including weird warnings about being too slow to log-in (time spent was under 5 seconds), but a refresh seems to do the trick. I am logged in using Chrome right now.

**Comment by hangler** [comment]
@karmour Just to double-check... any problems in the past week? If not, let's close this ticket. I know it's annoying to have to click the "Authenticate with IDIR" button, but it seems that the "hint" was causing errors in Chrome. cc: @robinwn

**Comment by karmour** [comment]
No issues this past week for me. There is a brief flicker prior to the keycloak authentication screen coming up, but that's it.

**Comment by aclowery** [comment]
Seems to be working fine in Chrome for me now!

**Comment by hangler** [comment]
👍
