### ISSUE TITLE
Status discrepancy between CallWeb and ESA

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#127]
The Status in the Exit Survey Admin App differs from the Status in CallWeb.

**Comment by hangler** [comment]
Hi @aclowery — would you please expand on this a bit? What are the discrepancies you're seeing?

**Comment by aclowery** [comment]
@hangler The individuals that appear as "Employee not exiting" in the ESA, still have "Exiting" status in CallWeb.

**Comment by hangler** [comment]
@aclowery Is this now behaving as expected? I think it should be, but kindly let me know.

**Comment by aclowery** [comment]
@hangler, statuses are updating correctly now.

**Comment by hangler** [comment]
Great!
