### ISSUE TITLE
Filter tag does not remove when clicking "Exiting Employees" in menu

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#131]
Non-critical bug: When a filter is engaged on the employee list page, clicking on the "Exiting Employees" link in the top-right corner resets the list to the full unfiltered employee list, but any existing filter tags remain visible, causing uncertainty on whether a filter is employed or not. See screen shot.

![image](https://user-images.githubusercontent.com/5818030/85909287-f1bb8b00-b7cd-11ea-8209-5881487a5a94.png)

**Comment by hangler** [comment]
Fixed on branch. Will deploy later today, after this morning's testing.

**Comment by hangler** [comment]
Deploying, should be ready for testing in a few mins.

**Comment by karmour** [comment]
Looks good!!

**Comment by hangler** [comment]
👍
