### ISSUE TITLE
CSV updates to existing record not pushed into Callweb

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#132]
Based on a test case I ran (telkey 115572201110), it appears that when the daily CSV makes updates to a non-final state record in the ESA, those updates are not pushed through into Callweb. There is a timeline entry on the record in the ESA for the updates, but the Callweb entry still has the old values.

Incidentally, I did notice that changes made to a record by the analyst in the ESA are pushed immediately to Callweb, so not sure what's interfering in the above case. Please investigate.

**Comment by karmour** [comment]
This appears to be fixed!

**Comment by hangler** [comment]
👍
