### ISSUE TITLE
Bug with default filters

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#135]
Found another bug with the default filters (sorry!). It appears that we can add both of the default date filters at once (previous month, previous fiscal year), but that only the one you clicked last will apply. Further, adding your own date filter acts the same -- if more than one date filter is active at once, only the latter-set filter applies. For example, if I click previous month first followed by previous fiscal year, the employee list only shows results for previous fiscal year. And if i re-click previous month at this point, it will now show results for the previous month but still show both filters engaged. See screen shots.

Previous month first, then Previous fiscal.
![image](https://user-images.githubusercontent.com/5818030/86067550-f8463e80-ba29-11ea-9af5-49fb4a7755b0.png)

Previous fiscal first, then Previous month.
![image](https://user-images.githubusercontent.com/5818030/86067587-10b65900-ba2a-11ea-99d8-e19d70785970.png)

Ultimately I think it's good that the app is only using one date-based filter at once. The issue is around how this is visualized in the app -- it's not necessarily clear that the app is only employing the last-set date filter when more than one appears active in blue. Could this be fixed so that it's more obvious that the second date filter replaces the first and is not co-active?

_Originally posted by @karmour in https://github.com/bcgov/ExitSurveyAdmin/issues/73#issuecomment-651432792_

**Comment by karmour** [comment]
Confirmed that now only one date filter appears at once! Thank you!

**Comment by hangler** [comment]
👍

**Comment by aclowery** [comment]
@hangler I have reopened this issue for the following reason:

If I first select the dates in the effective date to and from variables, then click add filter, the filter works. If I then decide to also add a filter to another variable afterwards for example Reason, once I add that filter, the date filter goes away and only the Reason variable remains.

**Comment by karmour** [comment]
Looks good to me! @aclowery how does it look to you now?

**Comment by hangler** [comment]
👍
