### ISSUE TITLE
Rename Exiting Employees link

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#136]
1. Could we rename the "Exiting Employees" link in the top-right of the landing screen to be "Employee Database" instead, since this leads to the full unfiltered list?
_Originally posted by @karmour in https://github.com/bcgov/ExitSurveyAdmin/issues/73#issuecomment-646894997_

**Comment by karmour** [comment]
Confirmed!

**Comment by hangler** [comment]
👍
