### ISSUE TITLE
Don't set Active Employees multiple times

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#138]
3. Clicking the "Active Employees" preset filter multiple times causes the filter to be 'added' multiple times. See screen shot at bottom of message.
_Originally posted by @karmour in https://github.com/bcgov/ExitSurveyAdmin/issues/73#issuecomment-646894997_

**Comment by karmour** [comment]
Confirmed!

**Comment by hangler** [comment]
👍
