### ISSUE TITLE
Reset status to Exiting when Not Exiting employee re-appears on CSV

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#139]
One exception to this logic is still in the works, I believe -- if a record is in an "Employee Not Exiting" state, but then reappears on the CSV, the ESA will set the status back to "Exiting" and update the record as per normal.

_Originally posted by @karmour in https://github.com/bcgov/ExitSurveyAdmin/issues/88#issuecomment-651401220_

**Comment by karmour** [comment]
As per #82, this is now working as expected. Thank you!
