### ISSUE TITLE
Update SURVEY_WINDOW_FLAG

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#141]
Email from @karmour:

The specs are relatively simple – we’d be looking for a variable to populate “SURVEY_WINDOW_flag” in Callweb, based on Status in the ESA. We’d be looking for the following:

Exiting = 0
Employee Not Exiting = 1
Out of Scope = 1
Survey: Expired = 1
Survey: Do Not Remind/Declined = 0
Survey: Complete = 0
Snail Mail Sent = 0
 
Basically, anyone with a 1 in this flag field would then have their survey closed by CW. (the Survey: Complete status is already handled via a different method in Callweb, so no need to set to a 1 for this one). This lets us completely control the survey open/close window by Status, which is of course already governed by dates and other factors in the ESA. Seems more efficient to me, which is a bonus.
 
With this change, we would then prefer to have the ESA be able to overwrite the “Employee Not Exiting” status with the “Exiting” status (i.e., Amelia’s original question in this thread), but only for the scenario where an employee dropped off the CSV and then at a future point reappeared with the same telkey parameters. It might be weeks or months or even 3 years later when the person next exits for real, but since the Leave count and Empl Rcd would be the same, the only way to let this person get invited and take the survey would be to have the Employee Not Exiting status be changed back to Exiting. This is the only scenario we care about right now that would require an exception to the otherwise-sacrosanct nature of the final statuses.

**Comment by karmour** [comment]
Addendums: 
1. OK to set the flag for Survey: Complete = 1, as per our email conversation
2. When the CallwebAPI updates the ESA database with a Survey:Complete status, is it possible to push that status and the flag back to Callweb, so that the two databases continue to align? Perhaps it is already set up to do that -- we tried testing this morning but have run into major issues with the Callweb server and cannot confirm what the conditions are. Can you confirm again how the API interacts with the Survey:Complete status at present?

**Comment by hangler** [comment]
Re: #2... I don’t think it pushes back to CallWeb at the moment. Would be easy adjustment to make.

**Comment by karmour** [comment]
Thanks Frank -- if easy, let's do that then. Having the databases aligned is ideal.

**Comment by hangler** [comment]
This should be working, as discussed and after looking at the code. Please let me know if not.

**Comment by karmour** [comment]
Confirmed that all statuses have the matching flag in Callweb, including Survey Complete = 1.

**Comment by aclowery** [comment]
Working as expected!
