### ISSUE TITLE
Fill _proj, _prepops, and _lastprepop in CallWebApi

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#144]
- [x] `_proj` should be a string configurable via the `appsettings.json` file
- [x] `_prepops` and `_lastprepop` should be strings in the format `YYYYMMDDHHMMSS` (24-hour clock, local time)

**Comment by hangler** [comment]
@robinwn @karmour As I'm starting on this, I only see a `_prepops` column — not a column named `_lastprepop`. I'm basing this on the schema @robinwn shared with me a while back, which I used to create the CallWeb model in the CallWebApi project. Can you kindly confirm that this column exists and is required?

**Comment by karmour** [comment]
Hmmmm if it was not in the schema, it's possible that the _lastprepop field is a calculated field in Callweb derived from the last entry in the _prepop field. In which case, we may only need to enter something in the _prepop field and it will take care of itself. Can we start based on that assumption?

**Comment by hangler** [comment]
Will do!

**Comment by robinwn** [comment]
confirmed _lastprepop is not in the ddl - must be purely calculated value - after the last μ

**Comment by hangler** [comment]
This is now done and I am going to push the CallWebApi code.

@robinwn NB, very important: I have made a change to `appsettings.json`. Instead of a `Telkey` section in the JSON file, there is now a `DefaultFields` section. It MUST have the following three items set:

* `AddFactor` (same as before)
* `MultiplyFactor` (same as before)
* `Proj` **new setting**: this value will be inserted into the `_proj` column upon CallWeb row creation

So, this will be need to be changed before the CallWebApi can work.

**Comment by robinwn** [comment]
appsettings.json updated for the dev environment.
I noticed that "AllowedHosts": "*", was dropped - no longer needed?

**Comment by robinwn** [comment]
Not sure if this belongs here or in a 'reconciliation' issue.
I ran the reconciliation to smoketest CallWebApi and it threw a connection error (i got the db name wrong in the new appsettings.json - since remedied)
The reconciliation page reported success rather than noting the api had failed.

**Comment by hangler** [comment]
> appsettings.json updated for the dev environment.
> I noticed that "AllowedHosts": "*", was dropped - no longer needed?

Yes, sorry — no longer needed per a conversation we had a few weeks ago.

**Comment by hangler** [comment]
> Not sure if this belongs here or in a 'reconciliation' issue.
> I ran the reconciliation to smoketest CallWebApi and it threw a connection error (i got the db name wrong in the new appsettings.json - since remedied)
> The reconciliation page reported success rather than noting the api had failed.
> 
> ps. once the db connection was corrected - reconcilation ran fine with no errors (in the stdout log)

By "reconciliation page" you mean the task log? Weird... should not show a success, of course. Will investigate.

**Comment by robinwn** [comment]
./exitsurvey/admin/admin page showed a green successful button below the blue 'Run reconciliation process' button.  Checking ./exitsurvey/admin/task-log-entries showed the red 'Fail' entry.

**Comment by hangler** [comment]
Ah, got it. Thanks. Will fix that.

**Comment by karmour** [comment]
The _proj and _prepops fields are populating correctly in Callweb now, and the _lastprepop field is calculating automatically. This appears working to me! Have not tested the bug with the Reconciliation process, but that seems like a separate issue.

**Comment by hangler** [comment]
In some ways it's not even a bug, it's showing "Success" to mean "the process was successfully triggered and ran to the end," not "there were zero errors during reconciliation." I should probably tweak it to indicate whether the process was itself successful, but that's more of an enhancement/improvement rather than a bug fix, strictly speaking.

**Comment by hangler** [comment]
This is done, the last-mentioned issue is in #147.
