### ISSUE TITLE
Expired status leads to extra Timeline entries

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#146]
I noticed in testing today that if a record has an Expired status, then a new entry appears in the Timeline every time a reconciliation or new CSV is imported. Given that we'll be importing daily, this will lead to very long and hard to read timelines for some records. Not a show-stopper for launch, but @hangler can you investigate when you have time later?

**Comment by hangler** [comment]
Looking into it.

**Comment by hangler** [comment]
Just making a note that when I fix this, we might want to manually purge the extra timeline entries... @robinwn what do you think?

**Comment by karmour** [comment]
Just noting that there are no Expired entries in PROD yet (we set the expiration threshold to 180 days for now), so you may not need to do anything after you change it. :-) Unless we want to clean up TEST...

**Comment by hangler** [comment]
@karmour Oh, that's good news! So it's more a theoretical problem at the moment, at least when it comes to production. Great 😄

**Comment by karmour** [comment]
@hangler Yes we noticed it in testing, so it will certainly become a problem when records start expiring in October.
