### ISSUE TITLE
Keycloak login prompt page says "Log in to MyWES"

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#149]
*Small Bug* When prompted to log in to the test and prod environments of the ESA, it redirects to a page that says "MyWES Authenticate with IDIR" and the tab title also says "Log in to MyWES". Although this message is inaccurate, in both instances once I login with my IDIR, I am successfully logged into the ESA (i.e., more of an aesthetics bug). Alternatively, the dev environment says BCSTATS. This might be more desirable, or perhaps EXIT SURVEY. @karmour do you have a preference for what this login prompt should read?

**Comment by karmour** [comment]
It's a Keycloak screen and if it can be customized for Exit Survey, then let's do that: "Exit Survey Admin"

If it cannot be customized per app, then we'll need something more generic that also works for MyWES, such as: "BC Stats Web Apps".

@robinwn please let us know what's possible. :)

**Comment by robinwn** [comment]
I've updated the Keycloak realm config to have a consistent naming of "BCStats".  The realm covers a collection of apps.  In Keycloak these apps are called 'clients'.  There are two client so far - MyWES and ExitSurveyAdmin.

**Comment by aclowery** [comment]
Thank you for fixing this Robin!
