### ISSUE TITLE
Exit Count not sorting as expected

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#150]
_Small bug_ - I noticed that if I sort on the Exit Count field in the ESA, it appears to sort on the first digit before moving on to the second digit, so values of 10 or higher appear in between those with Exit Counts of 1 or 2. Assuming this is because the values are stored as strings instead of integers.

**Comment by hangler** [comment]
Fixed. The same bug was on Record Count and Employee ID. Basically, they are represented as strings in the database (and so are sorted alphabetically by first character, so "10" comes before "2" because "1" < "2"), but should be sorted as ints (10 > 2).
