### ISSUE TITLE
Change order of CallwebAPI tasks to check Callweb for completion status first

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#151]
Callweb API is retrieving updates from the daily CSV prior to checking Callweb for Completion. This can lead to discrepancies between the ESA and Callweb if a user completes their survey within a day of updated variables for that record appearing on the CSV, because the API will update the non-final record in the ESA but those changes are correctly not pushed to the final record in Callweb. Then the changes are finalized in the ESA when the API pulls the final status from CW, making the discrepancy between the two databases permanent.

To resolve this issue, the order of tasks within the API should be changed. We think the API should check CW for completion status on existing records first, then check the CSV for new records/updates on non-final records, and then push any updates/changes to CW. Both databases should agree at all times, so this change will help ensure that.

Please let me know if anything is unclear, or if this change would result in other complications.

**Comment by hangler** [comment]
OK, this will now update an employee status before it reconciles the employee. An employee who has completed the survey will now not have their fields updated at all from the CSV; it will just skip the CSV reconciliation process altogether for that employee. I think this will fix this issue.

However, @karmour, I noticed another issue while testing this, which is that if the exit survey admin manually changes an employee status *away* from Survey Complete, the value of QCOMP for the corresponding row in CallWeb does not get updated. Maybe this is OK — is it really a situation that would happen, and should QCOMP be overridden if the survey has actually been completed at some point...? Might be a corner case we don't have to worry about? I bring it up only as your line about "both databases should agree at all times" echoes in my head :-)

**Comment by karmour** [comment]
Thanks Frank, that's fantastic! :-) 

As to your second scenario, I think this is highly unlikely to ever occur except by mistake. @aclowery can correct me if I'm mistaken. But I believe if someone ever asked to reset their survey, the first thing the analyst would do would be to re-initialize the entry in Callweb (which would wipe the QCOMP variable too) before doing anything in the ESA. It's probably slightly more likely that they forget to then update the ESA by changing the status back to "Exiting" -- @hangler remind me, will the ESA still check against Callweb after the record is in a "final" state? If not, this does seem like a corner case to me that we can try to manage on the business side.
