### ISSUE TITLE
Build and release Fixpack 2020 08

### ISSUE THREAD

**Issue by robinwn** [bcgov/ExitSurveyAdmin#155]
ready for dev

**Comment by robinwn** [comment]
@hangler  -  currently build service is showing the following typescript type error when building ClientApp.

```
  > exit-survey-admin@0.1.0 build {{build_dir}}\s\ClientApp
  > react-scripts build
  
  Creating an optimized production build...
  Failed to compile.
  
  {{build_dir}}/s/ClientApp/src/components/DisplayHelpers/Interface/Selects/CollectionSelect.tsx
  TypeScript error in {{build_dir}}/s/ClientApp/src/components/DisplayHelpers/Interface/Selects/CollectionSelect.tsx(94,37):
  Generic type 'ValueType' requires 2 type argument(s).  TS2314
  
      92 |   }
      93 | 
    > 94 |   protected onChange(selectedItems: ValueType<ICollectionSelectValue>): void {
         |                                     ^
      95 |     if (selectedItems != null && !Array.isArray(selectedItems)) {
      96 |       // Selected items is not an array. But for simplicity, we want to return
      97 |       // it as such everywhere, even when multiselect is not enabled. So
  
  
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
```

**Comment by hangler** [comment]
@robinwn @karmour I should have some time to take a look at this in the next few days. It should (hopefully!) be a relatively straightforward patch.

**Comment by hangler** [comment]
Unfortunately I cannot recreate this locally, even after nuking my `node_modules` directory and doing a `yarn install` followed by a `yarn build` in the `ClientApp` directory.

I do see, however, that the most recent typings for `ValueType` in the `react-select` type definitions repo *do* take 2 values... so there's something up with the versioning here.

I will see if removing `yarn.lock` fixes the problem.

**Comment by hangler** [comment]
OK, removing `yarn.lock`, then deleting `node_modules` and re-doing a `yarn install`/`yarn build` did indeed surface the issue, and I fixed it in the code in the simplest way possible (by basically allowing `any` as the second type argument, I'm afraid...).

My instinct is that the very existence of `yarn.lock` is to prevent these kinds of problems, and also that minor versions should not break stuff like this, but 🤷‍♂️. Will update the code on this branch and refer to this issue number.

**Comment by hangler** [comment]
@robinwn I'll leave this issue open. Please re-try and let me know if there are any other issues. Thanks!

**Comment by robinwn** [comment]
@hangler - Are you able to convert from yarn to npm.  Npm is what our build servers use and it's also what you have configured in the .csproj files

**Comment by hangler** [comment]
OK, will try — I should have time to take a look sometime this week.

**Comment by hangler** [comment]
If the npm / yarn thing is still an issue, will probably be fixed as part of move to OpenShift.
