### ISSUE TITLE
Warning Message in Task Log and Employee ID formatting

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#166]
The last Success in the task log was August 24, 2021. The 'Warn' task log messages began on August 26, 2021.
There were roughly 500 employees with errors at that time. As a reminder, Employee IDs are stored in the ESA as 6 digits with leading zeros for employee IDs less than 6 digits (i.e., 1234 would be 001234). I do believe the CSV data is unformatted and the ESA handles the formatting. 

These warning messages included employees with less than 6 digits and don't appear to have leading zeros (i.e., 1234 not matching up to the 001234 already in the database). 

For some of the September logs and following months, the number of employees with errors dropped to ~20 employees. The reason for these errors is because these employees appear in the ESA database as 1234 (i.e., were not formatted correctly upon entry into the ESA), so when the incoming data is trying to match it isn't able to because 001234 does not exist in the database.

**Comment by aclowery** [comment]
Turns out this is related to the way the file is being manually downloaded. Future improvements to ESA should look into running formatting on EmplID in order to eliminate this issue. If the csv is manually downloaded using outdated IE, the file is imported with leading zeros (on all variables). When I use Edge to download, I have to open the csv and proceed to save as, which removes leading zeros (on all variables). The only variable majorly affected by this difference is the employeeID because the data is unable to match depending on where the next file is saved from for importing.

**Comment by hangler** [comment]
Should be resolved as part of migration to PSA API.

**Comment by hangler** [comment]
Now using PSA API.
