### ISSUE TITLE
Add Health Status page showing API status

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#182]

**Comment by aclowery** [comment]
Tab is now visible, and I can see "ESA API is healthy." What are the other possible messages that we would expect to see?

**Comment by hangler** [comment]
That's it; if it doesn't show that after a reasonable amount of time (~1s or less), the API is not accessible. (This is the same behaviour as NJSA.)

**Comment by aclowery** [comment]
Ok, thank you!
