### ISSUE TITLE
Ability to filter by 'last modified date' in Employee database

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#193]
I know this variable contains date and time, but if possible the ability to filter by date (I don't care about the time in the filter). Reason: to see at a glance what might have occurred on a single day (or multiple days).

**Comment by aclowery** [comment]
This appears to be currently filtering for Created Date rather than Last Modified Date.

**Comment by aclowery** [comment]
Suggestion: We could leave that filter and rename to Created Date, and then add a filter that does actually filter for Last Modified Date as well.

**Comment by hangler** [comment]
Oops, this was an oversight in the code that my local testing didn't reveal! Would you like both filters?

**Comment by aclowery** [comment]
Sure, I'll take both - thank you!

**Comment by hangler** [comment]
On NJSA, we have this as "Import date", would that make sense here too?

**Comment by aclowery** [comment]
That works for me.

**Comment by hangler** [comment]
Looks correct after reviewing with @aclowery.
