### ISSUE TITLE
Non-Admins to see nothing (or less information) when logging in

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#194]
When non-admins log into the tool, they are able to enter and view some items on the different tabs. The data itself is not viewable (e.g., says "Loading..." on employee database screen, however, we would prefer less appears for them - or ideally nothing. Perhaps a page displaying a message that they do not have access to the site.

**Comment by hangler** [comment]
Looks correct after reviewing with @aclowery.
