### ISSUE TITLE
Bring over BC Assessment LDAP lookup case code from NJSA

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#203]

**Comment by hangler** [comment]
@aclowery For clarity, in ESA, do we only want to use this for setting the email, or do we also want to update other fields (first name, last name, location city) similarly to how we do in NJSA?

**Comment by aclowery** [comment]
Sure, let's try it how NJSA does with the additional fields from LDAP added to each record (if not in LDAP which is the case for many I believe, use what's in the API). Will there be any issues when we port over the PROD data and they don't have these LDAP variables in the data? Would it do LDAP lookups on them? Would they just default to blanks?

**Comment by aclowery** [comment]
Just realizing LDAP is the only way of getting emails for anyone as email address is not a variable in the CSV and likely not in the API either?

**Comment by hangler** [comment]
That's right, there's no concept of a "CHIPS" email as there is in NJSA

**Comment by hangler** [comment]
@aclowery:

> Sure, let's try it how NJSA does with the additional fields from LDAP added to each record (if not in LDAP which is the case for many I believe, use what's in the API). Will there be any issues when we port over the PROD data and they don't have these LDAP variables in the data? Would it do LDAP lookups on them? Would they just default to blanks?

* If we add them in as optional fields, there should not be an issue.
* Old records will default to NULLs for those fields.
* It would not do LDAP lookups, nor would it be straightforward to do them; I would suggest we just leave legacy rows as-is.

Hope that sounds OK!

**Comment by aclowery** [comment]
I think that sounds fine!

**Comment by hangler** [comment]
We looked at this together and confirmed it was working.
