### ISSUE TITLE
Do we need to check the status of Expired users in CallWeb?

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#208]
From the discussion here: https://github.com/bcgov/NewJobSurveyAdmin/issues/102

**Comment by aclowery** [comment]
The change to the admin interface should not affect the check in CallWeb. That would be a separate check as part of the import process I believe...

**Comment by hangler** [comment]
Discussion so far:

From @hangler:

> We're checking "Expired" [in ESA] as well... it's taking quite a bit of processing time.

From @aclowery:

> It likely is the case with Exit as well then. I only really noticed because the logs for NJSA are more descriptive, with the RefreshStatuses task displaying the number it checked e.g., "Tried to refresh 7216 employee statuses. 7216 were successful." Looking at the NJS data, it is the count of Active + Expired (+ the ones that were changed to Survey: Complete with the check). Exit has less information in the task log, so I wasn't exactly sure of the process, but if it is checking Expired statuses, it does not need to do so (in CallWeb at least). The Expired status is based on the # days defined in the Admin interface, so technically those could change.

From @karmour:

> Sorry to jump in, but the point about the expiration threshold in Admin being adjustable is probably why the system is checking Expired status upon refresh. If it wasn’t checking each time, then making a change to the expiry window would only affect those records which had not already expired, which may not be the desirable behaviour.

My response: can we instead only check Expired employees whose expiry threshold has been "undone" by a recent change to the expiry window?

**Comment by hangler** [comment]
@aclowery to clarify, if a user's survey is Expired, there's no way they can then complete the survey, right?

**Comment by aclowery** [comment]
An employee cannot access a survey when SURVEY_WINDOW_flag = 1. Which I believe the tool sets this value based on the status. That flag is 0 for Exiting status and 1 with any other status.

**Comment by hangler** [comment]
For now, we do NOT update Expired users. However, we should be un-expiring them if we change the expiry window.
