### ISSUE TITLE
Make sure timestamps show Pacific time

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#210]
e.g. TaskLogEntries.

**Comment by aclowery** [comment]
I believe the Employee page displays the correct timestamps but not the task logs.

**Comment by aclowery** [comment]
Just tested with a "Refresh from CallWeb". The result is good in the Employee Database and Task Log, i.e., Wed Mar 8 2023 15:07:44. A note that on the landing page, it appears as Wed, March 8, 2023 • 03:07:45 PST.

**Comment by hangler** [comment]
Confirmed fixed with @aclowery.
