### ISSUE TITLE
Keycloak Cookie not found

### ISSUE THREAD

**Issue by danebenal** [bcgov/ExitSurveyAdmin#216]
![Screenshot 2023-02-28 100946](https://user-images.githubusercontent.com/6244673/221942279-30ff14c0-bb39-4855-abd3-8fb625ad8ebb.png)

Since the upgrade to Keycloak Gold, ESA and NJSA sometimes encounter the above error. This seems to occur on the first login and after trying again, the issue does not reappear for some time (the next day?). We are able to work around this by using Private Mode.

**Comment by hangler** [comment]
@aclowery @danebenal Any evidence of this on ESA dev?

**Comment by danebenal** [comment]
I haven't encountered this, but I've only logged in twice. If @aclowery isn't encountering it, then I think it can be closed.

**Comment by hangler** [comment]
Great, we can re-open if necessary.
