### ISSUE TITLE
Implement draft retrieve from CallWeb API function

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#23]
Sub-task of #19.

**Comment by robinwn** [comment]
@hangler - I've been doing some thinking - telkey aka survey participant identity should be done in the Callweb api.  This keeps the survey software specific functionality with the survey api and the ExitSurveyAdmin can remain independant of the survey software used.
Contract: given employeeId, exitCount (EffDt month), return the survey unique identifier for this survey participant.
This also resolves the public vs private issues around telkey calculation.

**Comment by hangler** [comment]
Just to help me think this through:

1. Should we then change the `Telkey` column in the ExitSurveyAdmin app to be something like `SurveyId`? (We'll of course still need a way of linking the user back from the survey app.)

2. What about maybe also adding a column along the lines of `SurveySolution` which would hold, for now, something like `CallWeb`, but could hold some other identifier for another survey solution sometime later?

**Comment by hangler** [comment]
(Looping in @karmour.) To take this a bit further: while we're at it, can we even avoid the question of generating a telkey based on employee characteristics altogether? Why not just create a UUID for the employee's specific exit, insert that into the CallWeb database, and save it on the Employee in the ExitSurvey app as well? (Or would a proper UUID be too difficult to enter into the CallWeb login screen, if that's a requirement? And if we need a shorter randomly-generated ID, are we then concerned about key clashes? Would that bring us back to something based on employee data after all...?)

**Comment by hangler** [comment]
Also, while we resolve this question and the question of the Telkey generation, I'm going to try committing the CallWebApi code I have (which does not do Telkey generation, but should otherwise be ready) to TFS.

**Comment by hangler** [comment]
Done; see #12.
