### ISSUE TITLE
Ability to type in Date field filters (not only use the calendar)

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#231]
Ability to type in a date e.g., 2021/03/08, not just go through the calendar to locate the date in any date filter in the tool. Note that the old Exit tool and NJSA both have this ability.

**Comment by hangler** [comment]
Ugh, looks like this was a major regression in the latest version of the `react-datepicker` package, see e.g. the examples on this page: https://reactdatepicker.com

I'll try reverting to an earlier version.

**Comment by aclowery** [comment]
Reading the issue above, the note "Please note input works when you set up a range for the first time, when updating the date, issues arise." I realize is true, so it isn't impossible. It looks different from the previous version/other tools, as those bounce around on the visible calendar as you change and update your selected date as you're typing, whereas, this current version, you can type the exact date, once you complete the date, the calendar updates and you can add the filter.

If needed, this can be a lower priority item fix.

**Comment by aclowery** [comment]
This is working!

**Comment by hangler** [comment]
Great. There don't really seem to be many disadvantages to using the v3 rather than v4 of this library.
