### ISSUE TITLE
Different formatting for some variables?

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#233]
In test, records that were imported from the existing production seem to be going through a data update similar to the following for certain blank fields, I've noticed Address2 and Phone. They are being updated to a space. It seems like an unnecessary update to make in an employee's timeline.

![image](https://user-images.githubusercontent.com/58310027/223804026-2d334f5a-6cac-4025-bf95-11decc1b058a.png)

**Comment by hangler** [comment]
Hi @aclowery. I agree this might be a bit annoying. However, it's probably part of the switch from the CSV to PSA API.

Ideally, I'd prefer not to touch the code that does this comparison. I think it might be better to avoid adding extra rules that circumvent the data as delivered to us from the PSA API (or CSV). IMO it's better to just log it once and then move on going forward.

What do you think? Would it cause you undue issues with e.g. the data export...?

**Comment by hangler** [comment]
We discussed and determined this is OK for now. Maybe as a nice-to-have in the future.
