### ISSUE TITLE
Save buttons are no longer working

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#250]
Can no longer update employee's statuses, or change the threshold on the Admin Interface. The saves don't get "locked in"; it remains on the Cancel/Save screen and is not allowing changes to be made. See image.
![image](https://github.com/bcgov/ExitSurveyAdmin/assets/58310027/a23be7a0-01f4-4d7c-86eb-ee1fc85abf74)

**Comment by danebenal** [comment]
This has been resolved with changes from [commit 6cf3160ff7efa5dcca94a5112c73ed7bf17c3d22](https://github.com/bcgov/ExitSurveyAdmin/commit/6cf3160ff7efa5dcca94a5112c73ed7bf17c3d22).

This issue was introduced with changes to the URL. The API Gateway does not appear to support lowercase post.
