### ISSUE TITLE
LDAP lookup for employee emails

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#43]
@robinwn As we discussed, I will need some information (server, port, user ID, password) to make an LDAP lookup request to obtain an employee's email address. Feel free to send by whatever secure method makes sense!

**Comment by hangler** [comment]
```
adocommand = CreateObject("ADODB.Command")
adocommand.ActiveConnection = adoConnection
sqlTxt = "Select Mail from 'LDAP://" & Trim(ldapServer) & "/ou=bcgov,dc=idir,dc=BCGOV' where employeeID ='" & emplid & "'"
```

**Comment by hangler** [comment]
Discussed in call on 2020/04/27. @robinwn to investigate whether this is still the best way to get this info.

**Comment by robinwn** [comment]
The ldap service in BC Gov is found at 'idir.bcgov'

**Comment by hangler** [comment]
@robinwn Bit of a hiccup: System.DirectoryServices is not compatible with Mac/Linux platforms, throwing a `System.PlatformNotSupportedException: System.DirectoryServices is not supported on this platform`. Looking into this alternative: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard

**Comment by hangler** [comment]
The alternative solution works and I now have a working implementation. We can discuss in more detail tomorrow.
