### ISSUE TITLE
Draft data model

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#5]
Currently working on this here: https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model

**Comment by robinwn** [comment]
@hangler  I've added [EXIT_Users](https://github.com/bcgov/ExitSurveyAdmin/wiki/EXIT_Users) which has a couple of sub pages for the [DDL](https://github.com/bcgov/ExitSurveyAdmin/wiki/EXIT_Users-DDL) and [initial data review](https://github.com/bcgov/ExitSurveyAdmin/wiki/Existing-data-review)

**Comment by hangler** [comment]
Closing, but see #68.
