### ISSUE TITLE
What columns would we like on the exiting employee listing view?

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#59]
@karmour @aclowery — and please tag in anyone else: for the overview table listing exiting employees, which columns would we like included? I imagine name, email address, effective leave date, current status... any others?

**Comment by hangler** [comment]
@karmour Didn't get a chance to discuss this on our call just now, but it would be nice to get some feedback from anyone who might be using the ESA app. Very easy to change later, so could also wait till we're in the testing phase.

**Comment by karmour** [comment]
Hi Frank, your initial suggestions are all good. Let's also add in:
- Telkey
- Leave Code/Reason
- Job Type (forget the exact variable name)

And perhaps as you suggest we tweak this more when in testing? Thanks!

**Comment by hangler** [comment]
Great, thanks!

**Comment by karmour** [comment]
I'm not sure we have enough screen real estate for this, but it would be useful to have the Employee Record field visible on the employee list too, for instances where we have one employee leaving multiple jobs at the same time -- in this case there would be multiple entries with unique telkeys, but the Exit Count would be the same, so having the Employee Record visible would help the analyst differentiate, and would also validate that there is good reason for multiple telkeys (and therefore invitations to take the survey).

**Comment by hangler** [comment]
I think there's definitely enough screen real estate to show it :-) Now in the app.

**Comment by aclowery** [comment]
@hangler, I actually don't think the classification variable is necessary in the front view or as a filter. So can free up some real estate that way. Or if it's not too much trouble, we could replace this with Appointment Status instead? @karmour do you have any reasons to keep Classification in either the view or the filter?

**Comment by karmour** [comment]
No issues from me, @aclowery  -- I agree Classification is not that useful in day-to-day use. And Appointment Status would be more useful... but perhaps this is a lower priority fix. 

@hangler , if this is an easy fix and can be pushed through at the same time as your other push this afternoon, then please do so -- otherwise we can leave it for now.

Thanks!

**Comment by hangler** [comment]
Done on branch. Will deploy later today.

**Comment by hangler** [comment]
Deploying, should be ready for testing in a few mins.

**Comment by karmour** [comment]
Looks great!!

**Comment by aclowery** [comment]
Thank you for making the change, @hangler. I agree with Kyle, looks great.

**Comment by hangler** [comment]
👍
