### ISSUE TITLE
What is "FF_SUBMITTED"?

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#61]
Hey @robinwn, as I'm going through the Exit Survey 2016 code I came across some code that appears to set a flag called `FF_SUBMITTED`, but I'm not really clear what that is for. Can you help clear that up? Thanks!

**Comment by robinwn** [comment]
see in the legacy code (allUsers.vb) around line 301.  If the FF_SUBMITTED truthy value is true then the DT_SUBMITDATE value has been set.  A number of the columns shown in [Existing-data-review](https://github.com/bcgov/ExitSurveyAdmin/wiki/Existing-data-review) have 'flag' values that declare whether their value is void or set.

**Comment by hangler** [comment]
Thanks. OK, in turn... what does `DT_SUBMITDATE` indicate?

**Comment by robinwn** [comment]
```VBScript
For Each row As DataRow In myRows
        If Not checkSubmitted(row) Then
            processFlags(row)
        End If
Next
```
From the looks of 'processFlags' (also in allUsers.vb), it is where the core business rules are applied for newly exiting staff.
So if the incoming exiting staff row is not found to have a submitted date it's get 'processed'.
According to some of the comments:
- calculate days til leaving
- use exit count to generate unique telkey
- If no email, don't do mailout
- If email found and SMAIL flag checked and should get email then uncheck
- if you have an email address and haven't left yet then process for email message
- if time expires then set inactive

**Comment by hangler** [comment]
As per our discussion on 2020/04/27, this is part of a separate reconciliation step: mainly, an update to the ESA database. Will create a ticket to extract this logic into a separate step.
