### ISSUE TITLE
Extract variables from existing email templates

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#7]
@robinwn if you could send those to me that would be great. Thank you.

**Comment by robinwn** [comment]
@hangler  templates are on their way even now.

**Comment by hangler** [comment]
@robin got them. Thanks!

**Comment by hangler** [comment]
Added to the [wiki](https://github.com/bcgov/ExitSurveyAdmin/wiki/Use-cases:-Configuration-management).
