### ISSUE TITLE
Verify case where user appears twice in CSV

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#75]
In the Mar 31 extract, at least one user appears twice, one row right after the other. Verify that the app behaves correctly in this case.

**Comment by hangler** [comment]
It would appear that in this case, the `Exit Count` variable is the same. So we may indeed need to take into account `EffDt`...

**Comment by karmour** [comment]
I wonder if that's a mistake on the PSA side? It seems unlikely that one person could leave two positions on the same day - unless they are in a double role. And I think we would still only survey them once in that situation.

**Comment by hangler** [comment]
@karmour Yes, I think it is a bug. Let's definitely discuss tomorrow. In this case, it was the same person with what looks like two exits ~2 years apart. What happens is the app reads the first row, inserts the user, then reads the second row, and updates the user. But so many things get updated (including the `EffDt`) that it's clearly two separate exits.

**Comment by karmour** [comment]
Oh interesting - I am surprised that cases from 2 years ago are still on that list. I guess it never gets shortened, only longer... So yes, if the Leave number is not reliably updated, we'll have to factor in something else like EFFDT to the calculation for telkey -- maybe it ought to remain the same calc as previously?

**Comment by robinwn** [comment]
@karmour @hangler  I have a recollection of a discusion (i don't recall who) where we discussed cases where it could (has) happened that a person works in one ministry part time and another ministry as an auxiliary.  When they resign it can mean leaving two positions at the same time.

**Comment by hangler** [comment]
We discussed this on the call yesterday. Main questions:

* Is this a bug?
* Is the fact that the user has the same Exit Count on both rows a bug?

@karmour / @robinwn to follow up with Allan.

**Comment by hangler** [comment]
We got a resolution to this. Long story short, it is not a bug; we need to look at `Empl Rcd` as well. (See also #60 and #89.)
