### ISSUE TITLE
CallWeb MySQL version

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#79]
@robinwn The minimum version of MySQL supported by their EF Core connector is 5.7 (see [here](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html)). Does the CallWeb database match that?

**Comment by robinwn** [comment]
@hangler - confirmed Callweb is using a 5.7 MySQL - will be upgraded when it moves to a new server but that's probably at least 6mo's out.

**Comment by hangler** [comment]
Excellent, fingers crossed it'll work smoothly then! Thanks.
