### ISSUE TITLE
If a user is in a final state, don't update their fields

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#88]
Bug: currently a user's fields will be updated when their information changes in the CSV, even if they're in a final state. Don't do this.

**Comment by hangler** [comment]
We are now flagging the user if this happens.

**Comment by karmour** [comment]
This appears to be working correctly now -- records in a final state are not updated and instead an entry is made in the record's timeline, and a flag is set in the export.

One exception to this logic is still in the works, I believe -- if a record is in an "Employee Not Exiting" state, but then reappears on the CSV, the ESA will set the status back to "Exiting" and update the record as per normal.

**Comment by hangler** [comment]
We'll cover that in #139; closing this one.
