### ISSUE TITLE
Which fields should get pushed to Callweb?

### ISSUE THREAD

**Issue by karmour** [bcgov/ExitSurveyAdmin#94]
Here are the variables I think would need to be brought into Callweb. I've highlighted two new additions in italics.

_telkey (string >> links to Telkey field calculated within Admin app)
AEMAIL (string >> links with Email field in db)
AFNAME (string >> links with First Name field in db)
ALNAME (string >> links with Last Name field in db)
ALVREASON (string >> links with Reason field in db)
LVCODE (integer >> to be calculated in Admin app based on Reason field in db*)
AEFFDATE (string >> links with EFFDT field in db)
AMINISTRY (string >> links with Ministry field in db)
_APOSITION_TITLE (string >> links with Position Title field in db)
AEAPPTSTATUS (string >> links with Appointment Status field in db)_
ACURRENT_STATUS (string >> links to Current_Status field in ESA; used to identify employees not to send email reminders to, and potentially also to indicate when a user’s survey should expire)

The LVCODE calculation would have two possibilities -- either a 1 (for voluntary) or 2 (for involuntary) -- and would be dependent on a list of LVREASONs matched against these two codes. I can provide.

**Comment by hangler** [comment]
Thanks for this! Yes, if you have a list of the mapping between `LVREASON` and `LVCODE` that would be great.

**Comment by karmour** [comment]
Can't seem to figure out how to leave an attachment here, and the table formatting appears to be quite poor. Should I send you a file by email?

**Comment by hangler** [comment]
In theory you should be able to drag-and-drop a file into this comment box. If that doesn't work, then yes, please do email. Thank you!

**Comment by karmour** [comment]
[In-Scope Reasons.xlsx](https://github.com/bcgov/ExitSurveyAdmin/files/4629863/In-Scope.Reasons.xlsx)

Oh cool! Didn't realize that. :-)

Attached is a file that lists the Leave Reasons for both Regular and Auxiliary staff, and assigns a LVCODE to each possible reason. Note there is one Reason that I'm seeking clarification on from Allan (the Lay-off reason for included auxiliary staff), as I just want to make sure that it will appear as I have it recorded on this sheet (minus the asterisk note).

**Comment by karmour** [comment]
Confirmed -- the exact wording will be "Layoff (With Recall)" for this group. I will update the XLSX and re-attach. 

[In-Scope Reasons.xlsx](https://github.com/bcgov/ExitSurveyAdmin/files/4629943/In-Scope.Reasons.xlsx)

**Comment by karmour** [comment]
Hi Frank, I just realized that I was overlooking a sub-group of employees that will see certain questions in the survey, so it looks like we are going to have 3 total LVCODES. Attaching an updated spreadsheet yet again -- sorry about this. I think we have it right now. 

[In-Scope Reasons.xlsx](https://github.com/bcgov/ExitSurveyAdmin/files/4631592/In-Scope.Reasons.xlsx)

**Comment by karmour** [comment]
I've had some discussion with Allan O'Neill about the imperfect fit of using Classification to identify the position being left for the exiting employee -- often, the employee could be leaving multiple positions with the same classification. As a result, Allan has offered to push an additional variable into the daily CSV, called "Position Title". This will be available when the new feed starts up for June 1st. 

If not too troublesome, I'd like to adjust the list of fields pushed to Callweb, and replace Classification with Position Title. Frank if this is OK with you, I will go ahead and update the table above with the new field in Callweb.

**Comment by hangler** [comment]
Yup this is no problem at all.

**Comment by karmour** [comment]
@hangler Allan has confirmed that the Leave Groups or "Reasons" listed in the above Excel sheet are all the exact wording that we will see in the daily CSV feed.

**Comment by hangler** [comment]
Great, thanks for that.

**Comment by aclowery** [comment]
Hi Frank (@hangler), I have updated the original list to replace the previous classification variable with the new APOSITION_TITLE callweb variable.

**Comment by hangler** [comment]
These fields have been added to the CallWebApi.

I just want to confirm one thing, though. Currently the CSV extract does not have a "Position Title" field, just a numerical position code. @karmour @aclowery Do we know if this field will be added?

**Comment by karmour** [comment]
Hi Frank,

Confirming that the mapping of Leave Reasons to LVCODEs in the XLSX from May 14th above are correct. 

However, we are noticing in the records that came over to Callweb this morning that they all have LVCODE=1. There are about 28 records that should have been mapped to a 2 (based on Leave Reasons of "Job Ends/End of Recall Limit" and "Layoff (With Recall)"), and another 4 that should have been set to a 3 (based on Leave Reasons of "Redundant" and "Rejection on Probation"). 

Let me know if you need anything else to help investigate.

**Comment by karmour** [comment]
It's pretty easy! Do you want us to do so?

**Comment by hangler** [comment]
Yes, let's do that, since we're still so early in the testing. Thanks!

**Comment by karmour** [comment]
Done!

**Comment by karmour** [comment]
Hi @hangler, I'm re-opening this issue because I noticed in my data checks that one of the Reasons is not aligning with the expected LVCODE -- the "Job Ends/End of Recall Limit" Reason should be set to a 2, but I see it in Callweb as a 1. Can you fix that logic in the calculation? Thanks!

**Comment by hangler** [comment]
This was a bug that was still related to the capitalization issue — for some reason in the C# code I had a lower-case "l" for "Limit" :-) Fixing.

**Comment by karmour** [comment]
Confirmed it is now fixed. Thanks! 👍

**Comment by hangler** [comment]
👍
