### ISSUE TITLE
Allow both frontend and api to respond when proxied under a sub-uri

### ISSUE THREAD

**Issue by robinwn** [bcgov/ExitSurveyAdmin#99]
The web app (front end and api) needs to be configurable to allow it to be hosted under a variety of URIs.  These URIs typically are typically within a larger URI space within business website and are further differentiated by an environment, eg.  dev, test and production.
eg.
- https://<business_area>.gov.bc.ca/surveys/  (production)
- https://<business_area>.gov.bc.ca/dev/surveys/  (development)
- https://<business_area>.gov.bc.ca/test/surveys/  (testing)

On the api side, this can often be met by using appsettings.<environment>.json

On the client side routing is handled both serverside and clientside.  From what i've seen so far, the options seem to be limited to compile time injection of the base URI which ends up in the <base href="/some/path/here"> and hardcoded by React or Angular for the client side routing.

**Comment by hangler** [comment]
I believe the fix to #98 fixes this too. Closing this one up. @robinwn let me know if they're not actually linked and I'm misunderstanding something!
